require("prototypes.configuration")

require("prototypes.adv-reactors")
require("prototypes.heat-exchangers")
require("prototypes.steam-turbines")
require("prototypes.adv-fuel-cells")
require("prototypes.accumulators")
require("prototypes.solar-panels")
require("prototypes.geothermal-generator")
require("prototypes.rtg-generators")
